### ISSUE TITLE
HTML report missing figures on "Source" and "Dashboard" pages

### ISSUE THREAD

**Issue by mfscripts** [scheb/tombstone#25]
**Package version**: 1.5.2

**Description**

When generating the HTML report using the analyzer, the "Source" figures aren't populated and the headline figures on "Dashboard" are missing.

The tombstone entries are logged fine when they're hit and the analyzer appears to scan the codebase fine.

We've wrapped the call to the `tombstone()` function with our own static method, could this be the cause? `Tombstone::check();`

**To Reproduce**

1. Create the tombstone.yml file:
```
source_code:
  root_directory: /usr/local/www
logs:
  directory: ./tmp/tombstones
report:
  html: ./tmp/report/
```
2. Run the analyzer

**Additional Context**

"Source" screen:
![image](https://github.com/scheb/tombstone/assets/5589629/97539621-f37a-473b-8374-8ab500d2d145)

"Dashboard" screen:
![image](https://github.com/scheb/tombstone/assets/5589629/3094edc1-0e8a-4d26-9cff-e1990504d9c5)

**Comment by mfscripts** [comment]
I managed to trace this through in the end. For anyone else, you can set a configuration option within tombstone.yml to your own function name. For example:

```
tombstones:
  # Override the default Tombstone function name so it's parsed correctly on the analyzer
  parser:
    function_names: ['Tombstone::check']
```
